build:
  system_packages:
    - "libssl-dev"
  python_packages:
    - crewai==0.80.0
    - crewai-tools==0.14.0
    - langchain-community==0.3.7
    - llama-index-tools-yahoo-finance==0.2.0
    - yfinance==0.2.49
  run:
    - "curl -fsSL https://ollama.com/install.sh | sh"
